### ISSUE TITLE
Dataset file health.csv

### ISSUE THREAD

**Issue by scottshufe** [yazdanimehdi/Distraction_Fairness#1]
Hi, thanks for your excellent work!
May I ask where can I find the data file "health.csv" used in your code?
Thanks a lot!

**Comment by yazdanimehdi** [comment]
Hi,
you can find the accepted paper and all the relevant (much nicer) code and data in the following link:
https://github.com/yazdanimehdi/FairBiNN

**Comment by scottshufe** [comment]
Thank you so much for your quick reply and help! Best wishes!
